# Perspective camera for subbox, looking along z-axis
camera:
  type: perspective
  position: [14884.0, 17185.0, 24000.0]
  look_at: [14884.0, 17185.0, 29644.0]
  up: [0, 1, 0]
  fov: 32.0
  ortho_width: 5000.0
  image_width: 2048
  image_height: 2048

projections:
  - field: gas_density
    mode: column
